replicaCount: 1

tags:
  autoscaling: true
  loadBalancing: true

image:
  imageName: nvcr.io/nvidia/tritonserver:25.01-py3
  pullPolicy: IfNotPresent
  serverCommand: tritonserver
  serverArgs:
    - "--exit-on-error=false"
    - "--strict-readiness=false"
  env: {}

  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
      nvidia.com/gpu: 1
    requests:
      cpu: "100m"
      memory: "128Mi"
      nvidia.com/gpu: 1

    # nvidia.com/gpu: 0
    # nvidia.com/mig-1g.10gb: 0
    # nvidia.com/mig-2g.20gb: 0
    # nvidia.com/mig-3g.40gb: 0

  extraVolumeMounts:
    # - name: logs
    #   mountPath: /logs

  extraVolumes:
    # - name: logs
    #   emptyDir: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Model Repository Configuration (REQUIRED)
#
# Configure sources for model repository below.  Multiple repositories
# can be specified
#
# To download models from an S3 bucket, uncomment and configure below
# To specify a non-AWS S3 endpoint, use the form
#  s3://https://your-s3-endpoint:443/bucket/model_repository
#
#- --model-repository=s3://triton-inference-server-repository/model_repository
#
# Model Control Mode (Optional, default: none)
#
# To set model control mode, uncomment and configure below
#  for more details
#- --model-control-mode=explicit|poll|none
#
# Additional server args
#
# see https://github.com/triton-inference-server/server/blob/r24.05/README.md
#  for more details
modelRepository:
  type: local # Options: local, nfs, s3, gcs, azure

  local:
    mountPath: /models
  nfs:
    server: your-nfs-server
    path: /exported/models
    mountPath: /models # Used only for volumeMounts and CLI arg when type is nfs

  s3:
    bucket: your-s3-bucket
    region: your-region
    endpoint: https://s3.your-provider.com # Optional, for custom S3-compatible backends
    prefix: triton-models # Optional folder within the bucket

  gcs:
    bucket: your-gcs-bucket
    prefix: triton-models

  azure:
    container: your-container
    prefix: triton-models

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: triton-inference-sa

podAnnotations: {}

podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

inference_service:
  type: ClusterIP

metrics_service:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  monitor:
    endpoints:
      - port: metrics
        interval: 15s

inference_deployment:
  ports:
    http: 8000
    grpc: 8001
    metrics: 8002

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  metrics:
    - type: Pods
      pods:
        metric:
          name: avg_time_queue_us
        target:
          type: AverageValue
          averageValue: 50

nodeSelector: {}

tolerations: []

affinity: {}

# Prometheus-Operator ServiceMonitor support
# change enabled to 'true' to enable a ServiceMonitor if your cluster has
#  Prometheus-Operator installed
serviceMonitor:
  enabled: false

secret:
  create: true
  name: tis-model-repository-secret

  # List of environment variables to pull from the secret
  # These will be mounted into the container using `env.valueFrom.secretKeyRef`
  keys: []
