apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "triton-inference-server.fullname" . }}
  labels:
    {{- include "triton-inference-server.labels" . | nindent 4 }}
spec:
  {{- if .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "triton-inference-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "triton-inference-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        {{- if eq .Values.modelRepository.type "nfs" }}
        - name: models
          nfs:
            server: {{ .Values.modelRepository.nfs.server }}
            path: {{ .Values.modelRepository.nfs.path }}
            readOnly: false
        {{- end }}

      {{- if .Values.image.extraVolumes }}
        {{ toYaml .Values.image.extraVolumes | indent 8 }}
      {{- end }}

      serviceAccountName: {{ include "triton-inference-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.imageName }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          volumeMounts:
            {{- if eq .Values.modelRepository.type "nfs" }}
            - mountPath: {{ .Values.modelRepository.nfs.mountPath }}
              name: models
            {{- else if eq .Values.modelRepository.type "local" }}
            - mountPath: {{ .Values.modelRepository.local.mountPath }}
              name: models
            {{- end }}

          {{- if .Values.image.extraVolumeMounts }}
            {{ toYaml .Values.image.extraVolumeMounts | indent 12 }}
          {{- end }}

          args:
            - {{ .Values.image.serverCommand }}

            {{- if eq .Values.modelRepository.type "nfs" }}
            - --model-repository={{ .Values.modelRepository.nfs.mountPath }}

            {{- else if eq .Values.modelRepository.type "local" }}
            - --model-repository={{ .Values.modelRepository.local.mountPath }}

            {{- else if eq .Values.modelRepository.type "s3" }}
            {{- if .Values.modelRepository.s3.endpoint }}
            - --model-repository=s3://{{ .Values.modelRepository.s3.endpoint }}/{{ .Values.modelRepository.s3.bucket }}/{{ .Values.modelRepository.s3.prefix }}
            {{- else }}
            - --model-repository=s3://{{ .Values.modelRepository.s3.bucket }}/{{ .Values.modelRepository.s3.prefix }}
            {{- end }}

            {{- else if eq .Values.modelRepository.type "gcs" }}
            - --model-repository=gs://{{ .Values.modelRepository.gcs.bucket }}/{{ .Values.modelRepository.gcs.prefix }}

            {{- else if eq .Values.modelRepository.type "azure" }}
            - --model-repository=azure://{{ .Values.modelRepository.azure.container }}/{{ .Values.modelRepository.azure.prefix }}
            {{- end }}

            # 🔽 Consume extra server arguments here
            {{- range .Values.image.serverArgs }}
            - {{ . }}
            {{- end }}
            
          env:
          {{- if .Values.image.env }}
          {{- range $key, $value := .Values.image.env }}
            - name: {{ $key }}
              value: {{ $value }}
          {{- end }}
          {{- end }}

          {{- if and .Values.secret.create .Values.secret.keys }}
          {{- range .Values.secret.keys }}
                    - name: {{ .name }}
                      valueFrom:
                        secretKeyRef:
                          name: {{ $.Values.secret.name }}
                          key: {{ .name }}
          {{- end }}
          {{- end }}
                  
          ports:
            - containerPort: {{ .Values.inference_deployment.ports.http }}
              name: http
            - containerPort:  {{ .Values.inference_deployment.ports.grpc }}
              name: grpc
            - containerPort:  {{ .Values.inference_deployment.ports.metrics }}
              name: metrics
          
          livenessProbe:
            initialDelaySeconds: 15
            failureThreshold: 3
            periodSeconds: 10
            httpGet:
              path: /v2/health/live
              port: http

          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            httpGet:
              path: /v2/health/ready
              port: http

          startupProbe:
            periodSeconds: 10
            failureThreshold: 30
            httpGet:
              path: /v2/health/ready
              port: http

          resources: {{- toYaml .Values.image.resources | nindent 12 }}
              
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}