{{- if eq .Values.serviceAccount.create true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "triton-inference-server.serviceAccountName" . }}
  labels:
    {{- include "triton-inference-server.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
